-- ساختار دیتابیس ربات فروش کانفیگ
CREATE TABLE IF NOT EXISTS {p}settings (
  `k` VARCHAR(64) NOT NULL PRIMARY KEY,
  `v` LONGTEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}users (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `tg_id` BIGINT NOT NULL,
  `username` VARCHAR(64) NULL,
  `first_name` VARCHAR(128) NULL,
  `last_name` VARCHAR(128) NULL,
  `phone` VARCHAR(32) NULL,
  `email` VARCHAR(128) NULL,
  `balance` BIGINT NOT NULL DEFAULT 0,
  `total_paid` BIGINT NOT NULL DEFAULT 0,
  `is_banned` TINYINT(1) NOT NULL DEFAULT 0,
  `test_count` INT NOT NULL DEFAULT 0,
  `referrer_id` BIGINT NULL,
  `state` VARCHAR(64) NULL,
  `state_data` TEXT NULL,
  `note` VARCHAR(255) NULL,
  `last_seen` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  `email_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `phone_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `verify_kind` VARCHAR(16) NULL,
  `verify_target` VARCHAR(190) NULL,
  `verify_code` VARCHAR(16) NULL,
  `verify_token` VARCHAR(64) NULL,
  `verify_at` DATETIME NULL,
  `verify_tries` INT NOT NULL DEFAULT 0,
  `verified_at` DATETIME NULL,
  `miniapp_at` DATETIME NULL,
  `reseller_level` TINYINT(1) NOT NULL DEFAULT 0,
  `reseller_mark` VARCHAR(24) NULL,
  `reseller_credit` BIGINT NOT NULL DEFAULT 0,
  `reseller_discount` TINYINT(2) NOT NULL DEFAULT 0,
  `reseller_at` DATETIME NULL,
  `reseller_req` TINYINT(1) NOT NULL DEFAULT 0,
  `reseller_req_at` DATETIME NULL,
  `reseller_req_note` VARCHAR(400) NULL,
  `reseller_domain` VARCHAR(120) NULL,
  `reseller_brand` VARCHAR(80) NULL,
  `reseller_note_pub` VARCHAR(255) NULL,
  UNIQUE KEY `uq_tg` (`tg_id`),
  KEY `idx_ref` (`referrer_id`),
  KEY `idx_verify_token` (`verify_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}panels (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(128) NOT NULL,
  `type` VARCHAR(16) NOT NULL DEFAULT 'sanaei',
  `scheme` VARCHAR(8) NOT NULL DEFAULT 'https',
  `host` VARCHAR(190) NOT NULL,
  `port` INT NOT NULL DEFAULT 2053,
  `web_path` VARCHAR(190) NULL,
  `username` VARCHAR(128) NOT NULL,
  `password` VARCHAR(190) NOT NULL,
  `sub_base` VARCHAR(255) NULL,
  `node_host` VARCHAR(190) NULL,
  `inbound_ids` VARCHAR(190) NULL,
  `remark_prefix` VARCHAR(64) NULL,
  `username_mode` VARCHAR(16) NOT NULL DEFAULT 'random',
  `renew_mode` VARCHAR(16) NOT NULL DEFAULT 'reset_extend',
  `test_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `test_inbound_ids` VARCHAR(190) NULL,
  `test_single_inbound` TINYINT(1) NOT NULL DEFAULT 0,
  `test_volume_gb` DECIMAL(10,2) NOT NULL DEFAULT 1.00,
  `test_days` INT NOT NULL DEFAULT 1,
  `test_hours` INT NOT NULL DEFAULT 0,
  `test_limit` INT NOT NULL DEFAULT 1,
  `user_limit` INT NOT NULL DEFAULT -1,
  `users_created` INT NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `sort` INT NOT NULL DEFAULT 0,
  `session` TEXT NULL,
  `session_at` DATETIME NULL,
  `last_error` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}products (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `panel_id` INT UNSIGNED NOT NULL,
  `inbound_id` INT NULL,
  `name` VARCHAR(190) NOT NULL,
  `category` VARCHAR(64) NULL,
  `description` TEXT NULL,
  `volume_gb` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `days` INT NOT NULL DEFAULT 30,
  `ip_limit` INT NOT NULL DEFAULT 0,
  `device_limit` INT NOT NULL DEFAULT 0,
  `speed_up` INT NOT NULL DEFAULT 0,
  `speed_down` INT NOT NULL DEFAULT 0,
  `price` BIGINT NOT NULL DEFAULT 0,
  `old_price` BIGINT NULL,
  `stock` INT NOT NULL DEFAULT -1,
  `sold` INT NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `sort` INT NOT NULL DEFAULT 0,
  `deliver_mode` VARCHAR(8) NOT NULL DEFAULT '',
  `type` VARCHAR(8) NOT NULL DEFAULT 'fixed',
  `price_gb` BIGINT NOT NULL DEFAULT 0,
  `price_day` BIGINT NOT NULL DEFAULT 0,
  `min_gb` INT NOT NULL DEFAULT 1,
  `max_gb` INT NOT NULL DEFAULT 100,
  `min_days` INT NOT NULL DEFAULT 1,
  `max_days` INT NOT NULL DEFAULT 90,
  `created_at` DATETIME NOT NULL,
  KEY `idx_panel` (`panel_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}services (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT UNSIGNED NOT NULL,
  `tg_id` BIGINT NOT NULL,
  `panel_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NULL,
  `inbound_id` INT NOT NULL,
  `client_uuid` VARCHAR(64) NOT NULL,
  `client_email` VARCHAR(190) NOT NULL,
  `sub_id` VARCHAR(64) NULL,
  `sub_link` VARCHAR(512) NULL,
  `config_link` TEXT NULL,
  `volume_gb` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `days` INT NOT NULL DEFAULT 0,
  `expire_at` DATETIME NULL,
  `used_bytes` BIGINT NOT NULL DEFAULT 0,
  `is_test` TINYINT(1) NOT NULL DEFAULT 0,
  `status` VARCHAR(16) NOT NULL DEFAULT 'active',
  `renew_count` INT NOT NULL DEFAULT 0,
  `notified` VARCHAR(32) NULL,
  `last_sync` DATETIME NULL,
  `is_reseller` TINYINT(1) NOT NULL DEFAULT 0,
  `group_key` VARCHAR(32) NULL,
  `group_quota_gb` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  KEY `idx_user` (`user_id`),
  KEY `idx_email` (`client_email`),
  KEY `idx_group_key` (`group_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}orders (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT UNSIGNED NOT NULL,
  `tg_id` BIGINT NOT NULL,
  `product_id` INT UNSIGNED NULL,
  `service_id` INT UNSIGNED NULL,
  `type` VARCHAR(16) NOT NULL DEFAULT 'new',
  `amount` BIGINT NOT NULL DEFAULT 0,
  `discount_code` VARCHAR(64) NULL,
  `discount_amount` BIGINT NOT NULL DEFAULT 0,
  `final_amount` BIGINT NOT NULL DEFAULT 0,
  `status` VARCHAR(16) NOT NULL DEFAULT 'pending',
  `created_at` DATETIME NOT NULL,
  KEY `idx_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}transactions (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT UNSIGNED NOT NULL,
  `tg_id` BIGINT NOT NULL,
  `type` VARCHAR(16) NOT NULL DEFAULT 'deposit',
  `method` VARCHAR(16) NOT NULL DEFAULT 'card',
  `amount` BIGINT NOT NULL DEFAULT 0,
  `status` VARCHAR(16) NOT NULL DEFAULT 'pending',
  `ref` VARCHAR(64) NULL,
  `txid` VARCHAR(190) NULL,
  `receipt_file` VARCHAR(255) NULL,
  `note` VARCHAR(255) NULL,
  `admin_msg` TEXT NULL,
  `admin_id` BIGINT NULL,
  `created_at` DATETIME NOT NULL,
  `decided_at` DATETIME NULL,
  KEY `idx_user` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_txid` (`txid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}discount_codes (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `code` VARCHAR(64) NOT NULL,
  `type` VARCHAR(16) NOT NULL DEFAULT 'percent',
  `value` BIGINT NOT NULL DEFAULT 0,
  `max_uses` INT NOT NULL DEFAULT 0,
  `used` INT NOT NULL DEFAULT 0,
  `per_user` INT NOT NULL DEFAULT 1,
  `min_amount` BIGINT NOT NULL DEFAULT 0,
  `product_id` INT UNSIGNED NULL,
  `max_discount` BIGINT NOT NULL DEFAULT 0,
  `starts_at` DATETIME NULL,
  `expires_at` DATETIME NULL,
  `note` VARCHAR(190) NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL,
  UNIQUE KEY `uq_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}discount_uses (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `code_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `order_id` INT UNSIGNED NULL,
  `created_at` DATETIME NOT NULL,
  KEY `idx_code_user` (`code_id`,`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}gift_codes (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `code` VARCHAR(64) NOT NULL,
  `amount` BIGINT NOT NULL DEFAULT 0,
  `max_uses` INT NOT NULL DEFAULT 1,
  `used` INT NOT NULL DEFAULT 0,
  `expires_at` DATETIME NULL,
  `note` VARCHAR(190) NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL,
  UNIQUE KEY `uq_gift` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}gift_uses (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `code_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  KEY `idx_gift_user` (`code_id`,`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}tickets (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT UNSIGNED NOT NULL,
  `tg_id` BIGINT NOT NULL,
  `subject` VARCHAR(190) NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'open',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}ticket_messages (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ticket_id` INT UNSIGNED NOT NULL,
  `sender` VARCHAR(8) NOT NULL DEFAULT 'user',
  `text` TEXT NULL,
  `file_id` VARCHAR(255) NULL,
  `file_type` VARCHAR(16) NULL,
  `created_at` DATETIME NOT NULL,
  KEY `idx_ticket` (`ticket_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}tutorials (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(190) NOT NULL,
  `platform` VARCHAR(32) NOT NULL DEFAULT 'android',
  `content` TEXT NULL,
  `link` VARCHAR(255) NULL,
  `file_id` VARCHAR(255) NULL,
  `sort` INT NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}admins (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(64) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `name` VARCHAR(128) NULL,
  `role` VARCHAR(16) NOT NULL DEFAULT 'admin',
  `perms` TEXT NULL,
  `tg_id` BIGINT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `note` VARCHAR(255) NULL,
  `token` VARCHAR(64) NULL,
  `token_at` DATETIME NULL,
  `last_login` DATETIME NULL,
  `last_ip` VARCHAR(64) NULL,
  `created_at` DATETIME NOT NULL,
  UNIQUE KEY `uq_admin` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}logs (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `actor` VARCHAR(64) NULL,
  `action` VARCHAR(64) NOT NULL,
  `meta` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  KEY `idx_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}broadcasts (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(190) NULL,
  `kind` VARCHAR(24) NOT NULL DEFAULT 'text',
  `text` TEXT NULL,
  `file_id` VARCHAR(255) NULL,
  `file_type` VARCHAR(24) NULL,
  `buttons` TEXT NULL,
  `segment` VARCHAR(32) NOT NULL DEFAULT 'all',
  `pin` TINYINT(1) NOT NULL DEFAULT 0,
  `silent` TINYINT(1) NOT NULL DEFAULT 0,
  `total` INT NOT NULL DEFAULT 0,
  `sent` INT NOT NULL DEFAULT 0,
  `failed` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(24) NOT NULL DEFAULT 'done',
  `admin_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  KEY `idx_bc_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO {p}settings (`k`,`v`) VALUES
 ('deliver_mode','both'),
 ('shop_title','فروشگاه کانفیگ'),
 ('currency','تومان'),
 ('welcome_text','به فروشگاه خوش آمدید 🌟\nاز منوی زیر یکی از گزینه‌ها را انتخاب کنید.'),
 ('rules_text','• فروش سرویس فقط جهت استفاده قانونی است.\n• مسئولیت استفاده با خریدار است.'),
 ('support_username',''),
 ('force_channel',''),
 ('card_enabled','1'),
 ('card_number',''),
 ('card_holder',''),
 ('card_bank',''),
 ('crypto_enabled','1'),
 ('crypto_asset','USDT (TRC20)'),
 ('crypto_address',''),
 ('crypto_network','TRON / TRC20'),
 ('usd_rate','60000'),
 ('min_deposit','50000'),
 ('max_deposit','50000000'),
 ('test_enabled','1'),
 ('referral_bonus','0'),
 ('expire_notify_days','3'),
 ('traffic_notify_percent','85'),
 ('maintenance','0'),
 ('nowpay_enabled','0'),
 ('nowpay_api_key',''),
 ('nowpay_ipn_secret',''),
 ('nowpay_currency',''),
 ('nowpay_min_usd','5'),
 ('pay_gateways','[]'),
 ('pay_gw_migrated','0'),
 ('bot_texts','{}'),
 ('bot_text_rules','[]'),
 ('bot_buttons','[]'),
 ('btn_mode','reply'),
 ('btn_per_row','2'),
 ('rs_req_fee','0'),
 ('rs_req_fee_credit','0'),
 ('rs_req_fee_target','balance'),
 ('rs_req_auto','0'),
 ('rs_req_level','1'),
 ('rate_mode','auto'),
 ('rate_source','nobitex'),
 ('rate_unit','toman'),
 ('rate_markup','0'),
('rs_plans','[]'),
('rs_plans_on','1'),
 ('txc_auto_reject', '1'),
 ('txc_reject_low', '1'),
 ('txc_reject_notfound', '0'),
 ('nowpay_min_usd', '5'),
 ('rs_app_title', ''),
 ('btn_per_row', '2'),
 ('btn_mode', 'reply'),
 ('rate_round','500'),
 ('rate_ttl','60'),
 ('rate_raw','0'),
 ('rate_updated_at',''),
 ('rate_last_error',''),
 ('log_enabled','0'),
 ('log_chat_id',''),
 ('log_topics',''),
 ('log_events_off',''),
 ('log_backup','1'),
 ('log_silent',''),
 ('log_dedup_min','3'),
 ('log_auto_topic','1'),
 ('log_topic_retry','0'),
 ('order_stuck_minutes','10'),
 ('panel_density','normal'),
 ('panel_default_theme','dark'),
 ('sec_verify_mode','off'),
 ('sec_verify_email','0'),
 ('sec_verify_phone','0'),
 ('sec_verify_link','0'),
 ('sec_verify_required_for','buy'),
 ('sec_code_ttl','10'),
 ('sec_code_length','5'),
 ('sec_max_tries','5'),
 ('sec_resend_wait','90'),
 ('sec_mail_from',''),
 ('sec_mail_from_name',''),
 ('sec_mail_driver','mail'),
 ('sec_smtp_host',''),
 ('sec_smtp_port','587'),
 ('sec_smtp_user',''),
 ('sec_smtp_pass',''),
 ('sec_smtp_secure','tls'),
 ('sec_sms_driver','off'),
 ('sec_sms_url',''),
 ('sec_sms_method','GET'),
 ('sec_sms_body',''),
 ('sec_sms_headers',''),
 ('sec_block_multi_account','0'),
 ('sec_min_account_age','0'),
 ('sec_force_join_before_test','1'),
 ('sec_login_alert','1'),
 ('sec_login_max_fail','5'),
 ('sec_login_lock_min','15'),
 ('sec_session_idle_min','120'),
 ('rate_failover','1'),
 ('rate_live','1'),
 ('rate_assets','USDT,TON,TRX'),
 ('rate_custom_url',''),
 ('rate_custom_path',''),
 ('rate_custom_headers',''),
 ('rate_custom_unit','toman'),
 ('rate_custom_scale','1'),
 ('rate_src_used',''),
 ('crypto_addr_USDT',''),
 ('crypto_net_USDT','TRC20'),
 ('crypto_addr_TON',''),
 ('crypto_net_TON','TON'),
 ('crypto_addr_TRX',''),
 ('crypto_net_TRX','TRON'),
 ('miniapp_enabled','1'),
 ('miniapp_title',''),
 ('miniapp_accent','#6C8CFF'),
 ('miniapp_button','🚀 اپلیکیشن'),
 ('miniapp_show_menu','1'),
 ('miniapp_in_sections','0'),
 ('sub_local','1'),
 ('miniapp_rs_tab','0'),
 ('mute_start_text',''),
 ('wallet_receipt_any','1'),
 ('bc_batch','25'),
 ('bc_sleep','1200'),
 ('install_autodelete','1'),
 ('admin_miniapp','1'),
 ('txc_enabled','1'),
 ('txc_auto_approve','1'),
 ('txc_tolerance','3'),
 ('txc_timeout','15'),
 ('txc_bscscan_key',''),
 ('txc_etherscan_key',''),
 ('txc_tonapi_key',''),
 ('rs_enabled','1'),
 ('rs_price_gb','2000'),
 ('rs_price_day','500'),
 ('rs_base_fee','0'),
 ('rs_min_gb','1'),
 ('rs_max_gb','500'),
 ('rs_min_days','1'),
 ('rs_max_days','365'),
 ('rs_ip_limit','2'),
 ('rs_round','1000'),
 ('rs_l1_discount','10'),
 ('rs_l2_discount','20'),
 ('rs_l2_credit','500000'),
 ('rs_panels',''),
 ('rs_note',''),
 ('rs_requests_open','1'),
 ('gw_stale_hours','6');

-- ============================================================
-- احراز کارت بانکی (کارت به کارت)
-- هیچ داده‌ی حساسی ذخیره نمی‌شود: نه CVV2، نه رمز دوم، نه تاریخ انقضا
-- ============================================================
CREATE TABLE IF NOT EXISTS `{p}user_cards` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT UNSIGNED NOT NULL,
  `tg_id` BIGINT NULL,
  `pan` VARCHAR(19) NOT NULL,
  `pan_mask` VARCHAR(24) NULL,
  `holder` VARCHAR(80) NULL,
  `bank` VARCHAR(64) NULL,
  `sheba` VARCHAR(30) NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'pending',
  `note` VARCHAR(255) NULL,
  `uses` INT NOT NULL DEFAULT 0,
  `photo` VARCHAR(255) NULL,
  `admin_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `decided_at` DATETIME NULL,
  `last_used_at` DATETIME NULL,
  KEY `idx_uc_user` (`user_id`),
  KEY `idx_uc_status` (`status`),
  KEY `idx_uc_pan` (`pan`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `{p}settings` (`k`, `v`) VALUES
  ('cardauth_single','1'),('cardauth_photo','1'),('cardauth_photo_req','0'),
  ('cardauth_enabled','1'),('cardauth_required','1'),('cardauth_auto','0'),
  ('cardauth_max','3'),('cardauth_holder','1'),('cardauth_sheba','0'),('cardauth_luhn','1'),
  ('cardauth_note','شماره‌ی کارتی که قرار است با آن واریز کنید را ثبت کنید. واریز از کارت دیگران پذیرفته نیست.'),
  ('rs_wallet_only','0'),('rs_daily_limit','0'),('rs_month_limit','0'),
  ('rs_service_cap','0'),('rs_min_charge','0'),('rs_auto_suspend','0'),
  ('rs_sub_domain',''),('rs_welcome',''),('rs_support_id',''),
  ('rs_allow_test','0'),('rs_allow_rename','1'),('rs_allow_delete','1'),
  ('rs_allow_renew','1'),('rs_allow_edit','1'),('rs_show_price','1'),
  ('rs_hide_panel','1'),('rs_force_verify','0'),('rs_tos','')
ON DUPLICATE KEY UPDATE `v` = `v`;

/* انبار ملی — فروش دستی */
CREATE TABLE IF NOT EXISTS {p}stock_cats (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(120) NOT NULL,
  `icon` VARCHAR(16) NULL,
  `kind` VARCHAR(16) NOT NULL DEFAULT 'config',
  `description` TEXT NULL,
  `guide` TEXT NULL,
  `price` BIGINT NOT NULL DEFAULT 0,
  `old_price` BIGINT NULL,
  `days` INT NOT NULL DEFAULT 0,
  `volume_gb` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `sold` INT NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `sort` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  KEY `idx_sc_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {p}stock_items (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `cat_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `kind` VARCHAR(16) NOT NULL DEFAULT 'config',
  `title` VARCHAR(120) NULL,
  `payload` LONGTEXT NULL,
  `file_id` VARCHAR(255) NULL,
  `file_name` VARCHAR(120) NULL,
  `note` VARCHAR(255) NULL,
  `price` BIGINT NOT NULL DEFAULT 0,
  `status` VARCHAR(16) NOT NULL DEFAULT 'free',
  `user_id` INT UNSIGNED NULL,
  `tg_id` BIGINT NULL,
  `order_id` INT UNSIGNED NULL,
  `admin_id` INT NULL,
  `sold_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL,
  KEY `idx_si_cat` (`cat_id`),
  KEY `idx_si_status` (`status`),
  KEY `idx_si_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
